version: "2"
services:
  main:
    image: centos:7
#    ports:
#    - "80:80"
#    - "443:443"

    command: ['sleep', '10']
registries:
  docker:
    url: https://hub.docker.com/
    namespace: jmalacho
